// <auto-generated />
using System;
using IShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IShop.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("IShop.Models.Address", b =>
                {
                    b.Property<int>("userID");

                    b.Property<string>("AddressLine1");

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<string>("State")
                        .IsRequired();

                    b.HasKey("userID");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("IShop.Models.Basket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("productID");

                    b.Property<int>("userID");

                    b.HasKey("ID");

                    b.HasIndex("productID");

                    b.HasIndex("userID");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("IShop.Models.Category", b =>
                {
                    b.Property<int>("categoryID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Quantity");

                    b.Property<string>("categoryName");

                    b.HasKey("categoryID");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("IShop.Models.DiscountCard", b =>
                {
                    b.Property<int>("CardID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("type");

                    b.HasKey("CardID");

                    b.ToTable("Cards");
                });

            modelBuilder.Entity("IShop.Models.Product", b =>
                {
                    b.Property<int>("productID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Image")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<double>("Price");

                    b.Property<int>("categoryID");

                    b.Property<DateTime>("productDate");

                    b.HasKey("productID");

                    b.HasIndex("categoryID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("IShop.Models.User", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FullName");

                    b.Property<int>("cardID");

                    b.HasKey("userID");

                    b.HasIndex("cardID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IShop.Models.Address", b =>
                {
                    b.HasOne("IShop.Models.User", "User")
                        .WithOne("Address")
                        .HasForeignKey("IShop.Models.Address", "userID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IShop.Models.Basket", b =>
                {
                    b.HasOne("IShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("productID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IShop.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IShop.Models.Product", b =>
                {
                    b.HasOne("IShop.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("categoryID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IShop.Models.User", b =>
                {
                    b.HasOne("IShop.Models.DiscountCard", "discountCard")
                        .WithMany()
                        .HasForeignKey("cardID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
